# Generated by Django 3.2.12 on 2022-03-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220307_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_iamge',
            field=models.ImageField(blank=True, default='defalt.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
    ]
